# Generated by Django 2.0.1 on 2018-02-28 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bulletin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bulletin_type', models.CharField(choices=[('searching', 'Searching'), ('offering', 'Offering')], max_length=20, verbose_name='Type')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.TextField(max_length=300, verbose_name='Description')),
                ('contact_person', models.CharField(max_length=255, verbose_name='Contact person')),
                ('phone', models.CharField(blank=True, max_length=200, verbose_name='Phone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'Bulletin',
                'verbose_name_plural': 'Bulletins',
                'ordering': ('title',),
            },
        ),
    ]
