# Generated by Django 2.0.1 on 2018-03-04 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record2app', '0004_auto_20180228_1357'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flow_type', models.CharField(choices=[('out', '支出'), ('in', '收入')], max_length=10, verbose_name='流向')),
                ('item', models.CharField(max_length=50, verbose_name='項目')),
                ('amount', models.IntegerField(verbose_name='金額')),
                ('purch_date', models.DateField(auto_now=True, verbose_name='日期')),
            ],
        ),
    ]
