# Generated by Django 2.0.1 on 2018-03-04 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record2app', '0005_record'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='purch_date',
            field=models.DateField(verbose_name='日期'),
        ),
    ]
