# Generated by Django 2.0.1 on 2018-03-11 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record2app', '0006_auto_20180304_1550'),
    ]

    operations = [
        migrations.CreateModel(
            name='testClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typea', models.CharField(max_length=10, verbose_name='屬性A')),
                ('typeb', models.CharField(max_length=20, verbose_name='attrB')),
            ],
        ),
    ]
