# Generated by Django 2.0.1 on 2018-03-11 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record2app', '0007_testclass'),
    ]

    operations = [
        migrations.CreateModel(
            name='Costtype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typecode', models.CharField(max_length=5, verbose_name='類別代碼')),
                ('typename', models.CharField(max_length=20, verbose_name='類別')),
            ],
        ),
    ]
