# Generated by Django 2.0.1 on 2018-04-01 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record2app', '0008_costtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='flow_type',
            field=models.CharField(choices=[('支出', '支出'), ('收入', '收入')], max_length=10, verbose_name='流向'),
        ),
    ]
