# Generated by Django 2.0.4 on 2018-04-07 04:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('record2app', '0009_auto_20180401_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='建立時間'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='record',
            name='flow_type',
            field=models.CharField(choices=[('支出', '支出'), ('收入', '收入')], default='支出', max_length=10, verbose_name='流向'),
        ),
    ]
