# Generated by Django 2.0.4 on 2018-04-24 15:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record2app', '0011_auto_20180415_1611'),
    ]

    operations = [
        migrations.CreateModel(
            name='TobuyItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemname', models.CharField(max_length=20, verbose_name='名稱')),
                ('budget', models.IntegerField(verbose_name='預算')),
                ('addtime', models.DateTimeField(auto_now_add=True, verbose_name='加入時間')),
            ],
        ),
        migrations.AlterField(
            model_name='record',
            name='purch_date',
            field=models.DateField(default=datetime.date(2018, 4, 24), verbose_name='日期'),
        ),
    ]
