# Generated by Django 2.0.4 on 2018-04-26 16:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record2app', '0012_auto_20180424_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='purch_date',
            field=models.DateField(default=datetime.date(2018, 4, 26), verbose_name='日期'),
        ),
    ]
