# Generated by Django 2.0.4 on 2018-04-27 14:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record2app', '0013_auto_20180426_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='purch_date',
            field=models.DateField(default=datetime.date(2018, 4, 27), verbose_name='日期'),
        ),
    ]
