# Generated by Django 2.0.4 on 2018-04-27 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record2app', '0014_auto_20180427_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='tobuyitem',
            name='tobuy_type',
            field=models.CharField(choices=[('want', '想要'), ('need', '需要')], default='want', max_length=10, verbose_name='需要/想要'),
        ),
    ]
