# Generated by Django 2.0.4 on 2018-04-28 04:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record2app', '0015_tobuyitem_tobuy_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='tobuyitem',
            name='tobuy_date',
            field=models.DateField(null=True, verbose_name='預定購買日期'),
        ),
        migrations.AlterField(
            model_name='record',
            name='purch_date',
            field=models.DateField(default=datetime.date(2018, 4, 28), verbose_name='日期'),
        ),
    ]
