# Generated by Django 2.0.4 on 2018-04-28 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record2app', '0016_auto_20180428_0408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='flow_type',
            field=models.CharField(choices=[('in', '支出'), ('out', '收入')], default='in', max_length=10, verbose_name='流向'),
        ),
        migrations.AlterField(
            model_name='tobuyitem',
            name='tobuy_date',
            field=models.DateField(blank=True, null=True, verbose_name='預定購買日期'),
        ),
    ]
