# Generated by Django 2.0.4 on 2018-04-29 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record2app', '0018_auto_20180429_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='flow_type',
            field=models.CharField(choices=[('in', '收入'), ('out', '支出')], default='in', max_length=10, verbose_name='流向'),
        ),
    ]
