# Generated by Django 2.0.4 on 2018-05-12 04:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record2app', '0020_auto_20180509_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='purch_date',
            field=models.DateField(default=datetime.date(2018, 5, 12), verbose_name='日期'),
        ),
        migrations.AlterField(
            model_name='sport',
            name='sport_date',
            field=models.DateField(default=datetime.date(2018, 5, 12), verbose_name='日期'),
        ),
        migrations.AlterField(
            model_name='sport',
            name='user',
            field=models.CharField(choices=[('atheq33', '大親親'), ('qqqq', '小親親')], default='atheq33', max_length=10, verbose_name='姓名'),
        ),
    ]
