# Generated by Django 2.0.4 on 2018-05-30 16:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record2app', '0021_auto_20180512_0411'),
    ]

    operations = [
        migrations.AddField(
            model_name='sport',
            name='sport_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sport',
            name='sport_unit',
            field=models.CharField(choices=[('stairs', '層樓'), ('mins', '分鐘'), ('other', '其他')], default='stairs', max_length=10, verbose_name='單位'),
        ),
        migrations.AlterField(
            model_name='record',
            name='purch_date',
            field=models.DateField(default=datetime.date(2018, 5, 30), verbose_name='日期'),
        ),
        migrations.AlterField(
            model_name='sport',
            name='sport_date',
            field=models.DateField(default=datetime.date(2018, 5, 30), verbose_name='日期'),
        ),
    ]
