# Generated by Django 2.0.4 on 2018-05-30 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record2app', '0022_auto_20180530_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sport',
            name='sport_quantity',
            field=models.IntegerField(default=0, verbose_name='數量'),
        ),
    ]
