# Generated by Django 2.0.4 on 2018-05-30 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record2app', '0023_auto_20180530_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sport',
            name='sport_item',
            field=models.CharField(choices=[('stair', '爬樓梯'), ('bicycle', '腳踏車')], max_length=20, verbose_name='運動項目'),
        ),
    ]
