# Generated by Django 2.0.4 on 2018-04-15 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testmodel',
            name='testdate',
            field=models.DateField(max_length=10, verbose_name='Date'),
        ),
    ]
